apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: demo-microservice
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@github.com:rahulmotghare/platform-gitops.git
    targetRevision: main
    path: charts/demo-microservice

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true